# https://github.com/hetznercloud/csi-driver/blob/main/chart/values.yaml
hcloudToken:
  existingSecret:
    name: hcloud
    key: token
controller:
  hcloudVolumeDefaultLocation: "fsn1"
node:
  hostNetwork: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: NotIn
                values:
                  - ""
              - key: "instance.hetzner.cloud/is-root-server"
                operator: NotIn
                values:
                  - "true"
              - key: "csi.hetzner.cloud/location"
                operator: Exists
metrics:
  enabled: true
storageClasses:
  - name: hcloud-volumes
    defaultStorageClass: false
    reclaimPolicy: Delete
