# https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/chart/values.yaml
---
env:
  HCLOUD_TOKEN:
    valueFrom:
      secretKeyRef:
        name: hcloud
        key: token
  NODE_NAME:
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
  HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP:
    value: "true"
networking:
  enabled: true
metrics:
  enabled: true
