---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-2replicas
  namespace: mayastor
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "2"
provisioner: io.openebs.csi-mayastor
