---
machine:
  nodeLabels:
    kubernetes.io/os: linux # Just a label, so we can add more using JSON patch
  network:
    kubespan:
      enabled: true
  kubelet:
    registerWithFQDN: true
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/local
        type: bind
        source: /var/local
        options:
          - bind
          - rshared
          - rw
  sysctls:
    # https://www.talos.dev/v1.5/kubernetes-guides/configuration/storage/
    vm.nr_hugepages: "1024"
    # https://github.com/siderolabs/talos/issues/4654#issuecomment-1025125034
    vm.max_map_count: "262144"
    vm.overcommit_memory: "1"
    vm.swappiness: "1"
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.1  # newer versions keep crashing on dedicated servers, tested till v0.1.4
cluster:
  discovery:
    enabled: true
    registries:
      kubernetes: # Kubernetes registry is problematic with KubeSpan, if the control plane endpoint is routeable itself via KubeSpan.
        disabled: true
      service: {}
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  proxy:
    extraArgs:
      healthz-bind-address: "127.0.0.1:10256"
      metrics-bind-address: "0.0.0.0:10249"
  controllerManager:
    extraArgs:
      bind-address: "0.0.0.0"
  scheduler:
    extraArgs:
      bind-address: "0.0.0.0"
