---
machine:
  kubelet:
    registerWithFQDN: true
    extraArgs:
      rotate-server-certificates: true
    extraMounts:
      - destination: /var/storage/local
        type: bind
        source: /var/storage/local
        options:
          - bind
          - rshared
          - rw
  install:
    extensions:
      - image: ghcr.io/siderolabs/iscsi-tools:v0.1.4
cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
