# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
---
deployment:
  kind: DaemonSet
logs:
  general:
    level: INFO
service:
  annotations:
    load-balancer.hetzner.cloud/algorithm-type: least_connections
    load-balancer.hetzner.cloud/uses-proxyprotocol: true
    load-balancer.hetzner.cloud/use-private-ip: true
  spec:
    externalTrafficPolicy: Local
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
tolerations:
  - effect: NoSchedule
    operator: Exists
